### ISSUE TITLE
Not compatible with Gmail+ theme: mailbox switch button not visible

### ISSUE THREAD

**Issue by HLFH** [toteph42/identy_switch#6]
Gmail+ theme: https://roundcubeplus.com/skins/gmail_plus
With this theme, the mailbox switch button is not visible.
I have submitted a ticket on their end as they were supporting the former `ident_switch` plugin, and they need to support this fork that fixes may bugs and improves the whole thing.

**Comment by HLFH** [comment]
Three skins are hardcoded in https://github.com/toteph42/identy_switch/blob/master/assets/identy_switch.js: `larry`, `classic` and `elastic`. RoundcubePlus has added support for `ident_switch` but they would now need to support `identy_switch` as it is the successor of the former plugin.

**Comment by toteph42** [comment]
Yes, `identy_switch` plugin does only support `larry`, `classic`and `elastic' skin, because they're all open source. For all other skins (especially all commercial skins), some extra code need to be applied. If you want `Gmail+` to support this plugin, you need to contact them and ask them. If they provide me code (which must be open source), I can apply the code code extensions to my plugin.
