### ISSUE TITLE
IMAP special folders not specified by default for identy_switch IMAP accounts

### ISSUE THREAD

**Issue by HLFH** [toteph42/identy_switch#7]
> Erreur du plugin de planification des emails : le dossier de brouillon n'est pas spécifié.

I use this Email Scheduler plugin that was working with the `ident_switch` plugin.
https://roundcubeplus.com/plugins/email-schedule

It seems like the draft folder is not set for the created `identy_switch` IMAP accounts.

**Comment by HLFH** [comment]
I went to Paramètres > Préférences > Dossiers spéciaux to set my identy_switch IMAP accounts. They were not set. Should they not be set by default?

In the `identy_switch` table, instead of being empty by default, it should be:
drafts = Drafts
sent = Sent
junk = Junk
trash = Trash

**Comment by toteph42** [comment]
> Erreur du plugin de planification des emails : le dossier de brouillon n'est pas spécifié.

I don't know about this plugin. Please contact maintainer.

**Comment by toteph42** [comment]
> I went to Paramètres > Préférences > Dossiers spéciaux to set my identy_switch IMAP account's special folders. They were not set. Should they not be set by default?
> 
> In the `identy_switch` table, instead of being empty by default, it should be: drafts = Drafts sent = Sent junk = Junk trash = Trash

Some IMAP server automatically creates those folders if you create a mail account; others does not create any folder automatically. I think RoundCube is also able to create these folders, but I'm not sure about. 

At the end of the day my plugin cannot figure out which folders were available and to which folders the special folders should point (In Germany it happens a folder `Entwürfe` is automatically being created. This is the `Drafts` folder. I also saw `trash` folder instead of `Trash`) This must be set by user (as I mention in README.md under **Performace** section).
